# Generated by Django 5.2.3 on 2025-06-30 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='resumen',
            new_name='Ubicacion',
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.FileField(default=-3289, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=120)),
                ('empresa', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('inicio', models.TextField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia', to='dates.perfil')),
            ],
        ),
    ]
