# Generated by Django 5.2.3 on 2025-06-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_rename_resumen_perfil_ubicacion_perfil_telefono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='Ubicacion',
            new_name='resumen',
        ),
        migrations.AddField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(default=-3289, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(default='+52 000-000-0000', max_length=20),
        ),
    ]
