# Generated by Django 5.2.3 on 2025-07-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_rename_ubicacion_perfil_resumen_perfil_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='resumen',
            field=models.TextField(max_length=800),
        ),
    ]
