# Generated by Django 5.2.3 on 2025-07-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_perfil_imagen_alter_experiencia_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacionComplementaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('enlace', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('inicio', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
