# Generated by Django 5.2.3 on 2025-07-25 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0005_formacioncomplementaria_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacioncomplementaria',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='formacion', to='dates.perfil'),
            preserve_default=False,
        ),
    ]
